enableGlobalCache: false

packageExtensions:
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": ^2.11.0
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": ^2.11.0
  "@parcel/types@*":
    dependencies:
      "@parcel/core": ^2.11.0

yarnPath: .yarn/releases/yarn-4.4.1.cjs
